name: Main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: 'reiya24/${{ github.event.repository.name }}-${{ github.ref_name }}'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-workflow-queue@v1 #If the same workflow is already running from a previous commit, wait for it to finish
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --no-verification

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.1.0
      with:
        args: >
          -Dsonar.qualitygate.wait=true
          -Dsonar.projectKey=reiya_${{ github.event.repository.name }}
          -Dsonar.projectName=${{ github.event.repository.name }}
          -Dsonar.organization=reiya
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: reiya24
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Inject .env
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: '.env'
        fileDir: '.'
        encodedString: ${{ secrets.ENV }}

    - name: Docker build
      run: |-
        docker build -t "$DOCKER_IMAGE":"$GITHUB_SHA" .

    - name: push to container registry
      run: |-
        docker push "$DOCKER_IMAGE":"$GITHUB_SHA"

    - name: create docker-context
      uses: arwynfr/actions-docker-context@v2
      with:
        docker_host: 'ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}}:${{ secrets.SSH_PORT}}'
        context_name: 'remote'
        use_context: true
        ssh_cert: ${{ secrets.SSH_PUBLIC_KEY }}
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy docker-context
      run: |-
        export IMAGE_TAG=$GITHUB_SHA
        export DOCKER_IMAGE=$DOCKER_IMAGE
        export REPOSITORY_NAME=${{ github.event.repository.name }}
        docker compose -f deployment/docker-context/docker-compose.yaml up -d


    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://example.com|http://example.com
        max-attempts: 10 
        retry-delay: 10s 