name: Main

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-workflow-queue@v1 #If the same workflow is already running from a previous commit, wait for it to finish
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --no-verification

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.1.0
      with:
        args: >
          -Dsonar.qualitygate.wait=true
          -Dsonar.projectKey=${{ github.event.repository.name }}:${{ github.ref_name }}
          -Dsonar.projectName=${{ github.event.repository.name }}:${{ github.ref_name }}
          -Dsonar.organization=reiya
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}




    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Inject .env
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: '.env'
        fileDir: '.'
        encodedString: ${{ secrets.ENV_MAIN }}

    - name: Docker build
      run: |-
        docker build -t "$IMAGE":"$GITHUB_SHA" .

    - name: push to container registry
      run: |-
        docker push $IMAGE:$GITHUB_SHA

    - name: create docker context
      uses: arwynfr/actions-docker-context@v2
      with:
        docker_host: 'ssh://someone@example.domain.tld'
        context_name: 'dev-server'
        ssh_cert: ${{ secrets.SSH_CERT }}
        ssh_key: ${{ secrets.SSH_KEY }}

    - name: Deploy
      run: |-
       docker compose -f deployment/docker-context/docker-compose.yaml up -d